In [3]:
import pandas as pd
import numpy as np
dataset = pd.read_csv('learning_style_dataset.csv')
dataset.head()

quiz_score  time_spent learning_style
0          51          53       auditory
1          92          44         visual
2          14          20    kinesthetic
3          71          52         visual
4          60          32       auditory

In [6]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score

x = dataset[['quiz_score', 'time_spent']]
y = dataset['learning_style']

X_train, X_test, Y_train, Y_test = train_test_split(x, y, random_state=0, train_size=0.75)

clf = KNeighborsClassifier(n_neighbors=3)

clf.fit(X_train, Y_train)

Y_pred = clf.predict(X_test)

cm = confusion_matrix(Y_test, Y_pred)
print("Confusion Matrix:")
print(cm)

ac = accuracy_score(Y_test, Y_pred)
print(f"Accuracy: {ac}")

precision = precision_score(Y_test, Y_pred, average="micro")
print(f"Precision: {precision}")

recall = recall_score(Y_test, Y_pred, average="micro")
print(f"Recall: {recall}")

f1 = f1_score(Y_test, Y_pred, average="micro")
print(f"F1 Score: {f1}")

cv_scores = cross_val_score(clf, x, y, cv=5)
print(f"Cross-Validation Scores: {cv_scores}")
print(f"Mean Cross-Validation Score: {np.mean(cv_scores)}")

Confusion Matrix:
[[3729    0    0]
 [   0 4953    0]
 [   0    0 3818]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Cross-Validation Scores: [0.9999 1.     0.9999 1.     1.    ]
Mean Cross-Validation Score: 0.9999600000000001


In [7]:
time_spent = int(input("Time spent by the User: "))
quiz_scores = int(input("Scores obtained by the User: "))

input_data = pd.DataFrame([[quiz_scores, time_spent]], columns=["quiz_score", "time_spent"])

result = clf.predict(input_data)

print("Prediction result:", result[0])

Time spent by the User:  54
Scores obtained by the User:  34


Prediction result: kinesthetic


In [15]:
df = pd.read_csv('content_database.content_collection_csv.csv')
df.tail(6)

_id                  topic  \
0  665dc8500ddd15fd4aaf2a04            Percentages   
1  665dc8500ddd15fd4aaf2a05      Boats and streams   
2  665dc8500ddd15fd4aaf2a06           Age problems   
3  665dc8500ddd15fd4aaf2a07  Time, distance, speed   
4  665dc8500ddd15fd4aaf2a08          Number series   
5  665dc8500ddd15fd4aaf2a09     Pipes and cisterns   

                                             Article  \
0  https://www.geeksforgeeks.org/percentage-aptit...   
1  https://www.bing.com/search?q=boats+and+stream...   
2         https://byjus.com/govt-exams/age-problems/   
3     https://byjus.com/speed-distance-time-formula/   
4  https://www.geeksforgeeks.org/number-series-in...   
5  https://byjus.com/govt-exams/pipes-cistern-que...   

                        Youtube  
0  https://youtu.be/RWdNhJWwzSs  
1  https://youtu.be/yp2tgfwT3YU  
2  https://youtu.be/b9YMbDH02rM  
3  https://youtu.be/dHVK7IeLGT8  
4  https://youtu.be/iwpd_RkG-1U  
5  https://youtu.be/AHEFRed92zM

In [13]:
learning_style_topics = {
    'visual': ['Percentages', 'Boats and streams'],
    'auditory': ['Age problems', 'Time, distance, speed'],
    'kinesthetic': ['Number series', 'Pipes and cisterns']
}

if isinstance(result, (list, np.ndarray)):
    result = result[0] 

suggested_topics = learning_style_topics[result]
print(f"Suggested topics for {result} learners are: {suggested_topics[0]} & {suggested_topics[1]}")

chosen_topic = input(f"Which topic do you prefer? {suggested_topics[0]} or {suggested_topics[1]}: ")

if chosen_topic not in suggested_topics:
    print("Invalid topic chosen.")
else:
    resource_preference = input("Do you prefer YouTube or article?: ").lower()

    topic_row = df[df['topic'] == chosen_topic].iloc[0]
    if resource_preference == 'youtube':
        print(f"Here is the YouTube link for {chosen_topic}: {topic_row['Youtube']}")
    elif resource_preference == 'article':
        print(f"Here is the article link for {chosen_topic}: {topic_row['Article']}")
    else:
        print("Invalid preference chosen.")

Suggested topics for kinesthetic learners are: Number series & Pipes and cisterns


Which topic do you prefer? Number series or Pipes and cisterns:  Pipes and cisterns
Do you prefer YouTube or article?:  YouTube


Here is the YouTube link for Pipes and cisterns: https://youtu.be/AHEFRed92zM
